<a href="https://colab.research.google.com/github/Harshsurana-hub/Data-Science/blob/main/day-6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#py does not have array
# it has only list
# it is not fast
#NumPy (Numerical Python) is the foundational Python library for scientific computing and data analysis. It provides support for large,
#  multi-dimensional arrays and matrices, along with a massive collection of high-level mathematical functions to operate on these arrays efficiently.

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,'5'])
print(a)



['1' '2' '3' '4' '5']


In [6]:
import numpy as np
np_arr = np.array([3,3,3,3,3.3,'hello',0])
print(bool(np_arr[-1]))

True


In [ ]:
a = np.zeros((3,3),dtype=int)
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
a=np.empty(4,dtype=int)
print(a)

[   535864644            0 489626271845 493921239151]


In [3]:
a = np.arange(2,10)
print(a)

a = np.linspace(2,3)
print(a)

a = np.arange(2,3)
print(a)

NameError: name 'np' is not defined

In [ ]:
a = np.arange(1,12,2)
b=np.linspace(1,12,6,dtype=int)
print(a)
print(b.shape)
print(b)

[ 1  3  5  7  9 11]
(6,)
[ 1  3  5  7  9 12]


In [4]:
a= np.random.randint(2,3)
print(a)

NameError: name 'np' is not defined

In [ ]:
a = np.array([1,2,3,4])
b = np.array([9,8,7,6])
print(a*b)

# --- Explanation for error in cell 7V4gmSvKu8bZ ---
# The selected cell 'GaWqY6_Ak4DE' executed successfully.
# However, if you're asking about an error, it's likely related to cell '7V4gmSvKu8bZ'.
# In cell '7V4gmSvKu8bZ', the error 'ValueError: cannot reshape array of size 4 into shape (2,3)' occurred.
# This means you attempted to reshape an array with 5 elements (e.g., from `np.random.randint(2,15,5)`) into a shape of (2,3),
# which would require 2 * 3 = 6 elements. The number of elements in the original array must match the total elements required by the new shape.
# To fix this, you would need an array with 6 elements (e.g., `a = np.random.randint(2,15,6)`) to reshape it into `(2,3)`.

[ 9 16 21 24]


In [ ]:
a=np.random.randint(2,15,6) # Changed to 6 elements to match (2,3) reshape
print(a)

b = a.reshape((2,3))
print(b)

[3 8 7 7 8 4]
[[3 8 7]
 [7 8 4]]


In [ ]:
a= np.random.randint(2,15,6) # Changed to 6 elements to match (2,3) reshape
print(a)

b = a.reshape((2,3))
print(b)

z = a.transpose() # Transpose on a 1D array returns the array itself
print(z)

w = np.where(a == 2) # Corrected: np.where is a function, not a method of ndarray
print(w)

q = np.concatenate((a,b),axis=0) # Corrected: 'a' reshaped to 2D for concatenation with 'b'
print(q)

[ 9  8  4  5  7 13]
[[ 9  8  4]
 [ 5  7 13]]
[ 9  8  4  5  7 13]
(array([], dtype=int64),)


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [ ]:
a = np.random.randint(2,15,6)
b = np.random.randint(1,19,6)
print(a)
print(b)
c = np.where(b>2,b,a)
print(c)

[11 12  9  3  3  2]
[ 6 16 16  1  7  8]
[ 6 16 16  3  7  8]


In [ ]:
score = []
 days = ['mon','tue','wed','thr','fri','sat','sun']

 for i in range(7)
      x = input(f'give the input {days[i]}:')

hello world


In [ ]:
import numpy as np

n = int(input("Number of items: "))

prices = []

for i in range(n):
    prices.append(int(input()))

prices = np.array(prices)

print("Prices =", prices)

print("Total Bill =", np.sum(prices))
print("Average =", np.mean(prices))
print("Minimum =", np.min(prices))
print("Maximum =", np.max(prices))
print("Std Dev =", np.std(prices))

print("Sorted  =", np.sort(prices))
print("Unique  =", np.unique(prices))

print("Items > 100   =", prices[np.where(prices > 100)])


In [ ]:
matrix = np.random.randint(1, 90, size=(5, 5))

row_matrix = np.mean(matrix,axis=1)
print(row_matrix)

colloum_matrix = np.mean(matrix,axis=0)
print(colloum_matrix)

b = np.where(matrix%2==0,-1,matrix)
print(b)

row_sort = np.sort(matrix,axis=1)
print(row_sort)

colloum_sort = np.sort(matrix,axis=0)
print(colloum_sort)

row_sum = np.sum(matrix,axis=1)
print(row_sum)

colloum_sum = np.sum(matrix,axis=0)
print(colloum_sum)

colloum_count = np.sum(b<0)
print(colloum_count)

[39.8 68.  61.8 37.4 47. ]
[48.6 39.8 69.  59.6 37. ]
[[73 -1 57 -1 19]
 [55 -1 -1 85 -1]
 [-1 65 -1 -1 -1]
 [-1 -1 -1 43 -1]
 [27 -1 -1 -1 -1]]
[[ 8 19 42 57 73]
 [52 55 70 78 85]
 [ 6 65 74 78 86]
 [ 2 10 43 54 78]
 [27 36 50 58 64]]
[[ 2  8 57 42  6]
 [27 10 58 43 19]
 [55 52 74 50 36]
 [73 64 78 78 54]
 [86 65 78 85 70]]
[199 340 309 187 235]
[243 199 345 298 185]


AttributeError: module 'numpy' has no attribute 'count'

In [2]:
stock = np.random.randint(1, 101, size=(5, 5))
print(stock)
demand = np.random.randint(1,101,size=(5,5))
print(demand)
stock_sum_colloum = np.sum(stock,axis=0)
print(stock_sum_colloum)
demand_sum_colloum = np.sum(demand,axis=0)
print(demand_sum_colloum)
remaining_stock = stock-demand
print(remaining_stock)

b = np.where(remaining_stock<0,0,remaining_stock)
print(b)

shortage = remaining_stock - b
print(shortage)
Shortage = np.sum(shortage,axis=0)
print(Shortage)

c = np.where(stock<0,-1,stock)
print(c)

pro_zero = np.sum(c<0)
print(pro_zero)

NameError: name 'np' is not defined